# Generated by Django 3.0.4 on 2020-03-21 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0003_auto_20200321_1035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Rating',
        ),
    ]
